-- 코드를 입력하세요
SELECT 
    u.USER_ID, 
    u.NICKNAME, 
    CONCAT_WS(' ', u.CITY, u.STREET_ADDRESS1, u.STREET_ADDRESS2) AS 전체주소,
    CONCAT_WS(
        '-', 
        SUBSTRING(u.TLNO, 1, 3), 
        SUBSTRING(u.TLNO, 4, 4), 
        SUBSTRING(u.TLNO, 8, 4)
    ) AS 전화번호
FROM USED_GOODS_USER u
INNER JOIN (
    SELECT b.WRITER_ID
    FROM USED_GOODS_BOARD b
    GROUP BY b.WRITER_ID
    HAVING COUNT(*) >= 3
) w ON w.WRITER_ID = u.USER_ID
ORDER BY u.USER_ID DESC