-- 코드를 입력하세요
SELECT p.PRODUCT_CODE, (s.SUM * p.PRICE) AS SALES
FROM PRODUCT p
INNER JOIN(
    SELECT PRODUCT_ID, SUM(SALES_AMOUNT) AS SUM 
    FROM OFFLINE_SALE
    GROUP BY PRODUCT_ID
 ) s ON s.PRODUCT_ID = p.PRODUCT_ID
ORDER BY SALES DESC, p.PRODUCT_CODE