-- 코드를 입력하세요
SELECT
    ugb.TITLE,	
    ugb.BOARD_ID,	
    ugr.REPLY_ID,	
    ugr.WRITER_ID,	
    ugr.CONTENTS,	
    LEFT(ugr.CREATED_DATE, 10) as CREATED_DATE
FROM USED_GOODS_BOARD ugb
INNER JOIN USED_GOODS_REPLY ugr 
ON ugb.BOARD_ID = ugr.BOARD_ID
WHERE LEFT(ugb.CREATED_DATE, 10) LIKE '2022-10%' 
ORDER BY ugr.CREATED_DATE, ugb.TITLE