-- 코드를 입력하세요
SELECT a.USER_ID, a.PRODUCT_ID
FROM (
    SELECT USER_ID, PRODUCT_ID, COUNT(*) AS COUNT
    FROM ONLINE_SALE
    GROUP BY USER_ID, PRODUCT_ID
) AS a
WHERE a.COUNT > 1
ORDER BY USER_ID, PRODUCT_ID DESC