-- 코드를 입력하세요
SELECT 
    DATE_FORMAT(DATETIME, '%k') AS HOUR, 
    COUNT(DATE_FORMAT(DATETIME, '%k')) AS COUNT
FROM ANIMAL_OUTS
WHERE DATE_FORMAT(DATETIME, '%k') >= 9 AND DATE_FORMAT(DATETIME, '%k') <= 19
GROUP BY DATE_FORMAT(DATETIME, '%k')
ORDER BY DATE_FORMAT(DATETIME, '%H')
