-- 코드를 입력하세요
SELECT distinct c.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR c
INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY rh ON c.CAR_ID = rh.CAR_ID
WHERE c.CAR_TYPE = '세단' AND DATE_FORMAT(rh.START_DATE, '%m') = '10'
ORDER BY c.CAR_ID DESC